# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emms < Formula
  desc "Manage media for eick.com"
  homepage "https://eick.com"
  version "0.0.010"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/andreweick/emms/releases/download/v0.0.010/emms_0.0.010_Darwin_arm64.tar.gz"
      sha256 "7d91ec77ba391187e1d1bebd0af8a2c0557d93f730bcde2713db0fd1f7b86f73"

      def install
        bin.install "emms"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/andreweick/emms/releases/download/v0.0.010/emms_0.0.010_Darwin_x86_64.tar.gz"
      sha256 "d68eff51a4a609cd846e63c45df6865f380e92a8ecee3f91377d972757182a69"

      def install
        bin.install "emms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/andreweick/emms/releases/download/v0.0.010/emms_0.0.010_Linux_x86_64.tar.gz"
      sha256 "5c949be995feb079ccd2f1ff9d4941d8bbd59c60eceedf6b1dbd79ffd62662ba"

      def install
        bin.install "emms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreweick/emms/releases/download/v0.0.010/emms_0.0.010_Linux_arm64.tar.gz"
      sha256 "eece025cfa799366d2216ceb225e2fbb3afb1971b48bc22c94f17a7a462e98c5"

      def install
        bin.install "emms"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  conflicts_with "goreleaser-pro"

  test do
    system "#{bin}/goreleaser -v"
  end
end
