# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emms < Formula
  desc "Manage media for eick.com"
  homepage "https://eick.com"
  version "0.0.015"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/andreweick/emms/releases/download/v0.0.015/emms_0.0.015_Darwin_arm64.tar.gz"
      sha256 "2b3a14aeeb688be361a2025bc0f2ff1aafd7a18f5b65a91d7277eee03f946aec"

      def install
        bin.install "emms"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/andreweick/emms/releases/download/v0.0.015/emms_0.0.015_Darwin_x86_64.tar.gz"
      sha256 "670f5fb5facdf0f1c1d4a926a13e1c8cd73fcd255e71836122738416a9ef56c5"

      def install
        bin.install "emms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreweick/emms/releases/download/v0.0.015/emms_0.0.015_Linux_arm64.tar.gz"
      sha256 "9c518a1725d8d93516c877066979edc0a3cd002fa8c2c0c3598e8d048016bfbc"

      def install
        bin.install "emms"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/andreweick/emms/releases/download/v0.0.015/emms_0.0.015_Linux_x86_64.tar.gz"
      sha256 "97f65bb2ea29525224f0750f707c1d3e58ffaa985748b2a7cfd27bc77f71cc80"

      def install
        bin.install "emms"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  conflicts_with "goreleaser-pro"

  test do
    system "#{bin}/goreleaser -v"
  end
end
